### ISSUE TITLE
Errors running the docker version

### ISSUE THREAD

**Issue by felipehcoutinho** [julvi/HostPhinder#1]
I have a large dataset with thousands of viral genomes to run, so it is not feasible for me to use the web version. Therefore I have been trying to run it with the docker container that you made available.

I could not find any documentation on how to run the standalone version, so If I missed something please let me know.

I tried different ways of running it with two commands:
`sudo docker run julvi/hostphinder scripts/wrap_hostPhinder_cl.sh -i JF704094.fsa -t genus`
Which returned the following errors:
```
Traceback (most recent call last):
  File "scripts/findtemplate_scipy.py", line 105, in <module>
    outputfile = open(args.outputfile,"w")
IOError: [Errno 2] No such file or directory: 'results/JF704094.fsa_genus_pred_16mers_evalue0.05'
scripts/wrap_hostPhinder_cl.sh: line 67: results/JF704094.fsa_genus_pred_16mers_evalue0.05: No such file or directory
JF704094.fsa    No_significant_match_found
```

and 

`sudo docker run julvi/hostphinder /scripts/findtemplate_scipy.py -i JF704094.fsa -t genus`

which returned:

> # Reading database of templates and ckecking for database integrity
> Traceback (most recent call last):
>   File "/scripts/findtemplate_scipy.py", line 147, in <module>
>     if any(ulength == 0 for ulength in templates_ulengths.values()):
> NameError: name 'templates_ulengths' is not defined

I am aware that its been several years since you published this but I would really appreciate your help on getting this to run on my dataset

**Comment by andynet** [comment]
Hello there,

I am not the developer of this tool, but I think I can offer the solution. Quickfix is here:
```
docker run \
    -v /data/projects/pheri/hostphinder/input:/data \
    -v /data/projects/pheri/hostphinder/results:/results \   
    julvi/hostphinder /scripts/wrap_hostPhinder_cl.sh \
        -i /data/test.fasta \
        -t genus
```
just change the directories `/data/projects/pheri/hostphinder/input` and `/data/projects/pheri/hostphinder/results` to some existing directories on your local machine (input directory should contain the fasta file with the sequence you want to analyze).

(Limited) Explanation:
The first error is there because the docker image does not have the `/results` directory created and the script `scripts/wrap_hostPhinder_cl.sh` has the lines for creating the directory commented out. The second option `-v` will mount the local directory into an image's `/results` directory.
The first option `-v` mounts the local directory containing sequences to the docker image, so we can supply custom datasets for prediction.

**Comment by felipehcoutinho** [comment]
Thanks for the input!
